# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - job-shop-collection-api

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_update_database:
    name: Build and Update Database
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'

    - name: Install dependencies
      run: dotnet restore --source https://api.nuget.org/v3/index.json
      
    - name: Build with dotnet
      run: dotnet build --configuration Release --no-restore

    - name: Publish with dotnet
      run: dotnet publish -c Release --no-build -o ${{env.DOTNET_ROOT}}/myapp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp

# The server and database is open to public, so a login is not necessary
#    - name: Login to Azure
#      id: login_azure
#      uses: Azure/login@v1
#      with:
#        creds: ${{ secrets.AZURE_CREDENTIALS_DATABASE_PUBLISHER }}

    - name: Install dotnet-ef
      run: dotnet tool install --global dotnet-ef

    - name: Run dotnet ef database update
      run: |
        $Env:ConnectionStrings__JobShopCollectionConnectionString = "${{ secrets.AZURE_SQL_CONNECTION_STRING }}"
        dotnet ef database update --configuration Release -p job-shop-collection-api.Data -s job-shop-collection-api

#    - name: Logout of Azure
#      if: ${{ always() && steps.login_azure.outcome == 'success' }}
#      continue-on-error: true
#      run: az logout

  deploy:
    name: Deploy
    runs-on: windows-latest
    needs: [build_and_update_database]
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: .net-app

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'job-shop-collection-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_574958f0102a4774a2695bd61d4bf111 }}
        package: .
