name: Linode - Build and deploy job-shop-collection-api

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_update_database:
    name: Build and Update Database
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Install dependencies
      run: dotnet restore --source https://api.nuget.org/v3/index.json
      
    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Publish with dotnet
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp /p:PublishProfile=FolderProfile

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp

    - name: Install dotnet-ef
      run: dotnet tool install --global dotnet-ef

    - name: Run dotnet ef database update
      run: |
        export ConnectionStrings__JobShopCollectionConnectionString="${{ secrets.LINODE_SQL_CONNECTION_STRING }}"
        dotnet ef database update --configuration Release -p job-shop-collection-api.Data -s job-shop-collection-api

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build_and_update_database]
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: .net-app

    - name: Upload
      env:
        remote_host: ${{ secrets.LINODE_HOST }}
        remote_port: ${{ secrets.LINODE_PORT }}
        remote_user: ${{ secrets.LINODE_USER }}
        remote_key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
        local_dir: "."
        remote_dir: ${{secrets.LINODE_DIRECTORY}}
      run: |
        mkdir ~/.ssh
        echo "$remote_key" > ~/.ssh/gh_actions_key
        chmod 600 ~/.ssh/gh_actions_key
        rsync -avzr --delete -e "ssh -p ${remote_port} -i ~/.ssh/gh_actions_key -o StrictHostKeyChecking=no" ${local_dir} ${remote_user}@${remote_host}:${remote_dir}
